baseURL = "/"
title = "SquareCows"
languageCode = "en-us"
defaultContentLanguage = "en"
paginate = "7"
theme = "spectral"

[params]
fancyTitle = '<img height="80" src="img/logo.png" alt="logo"/>' # title for frontpage, may include image
logo = '<img height="50" src="https://squarecows.com/img/logo.png" alt="logo"/>' # title for frontpage, may include image
copyright = "Ric Harvey"
description = 'Cloud Architecture and Economics for AWS'
startbuttonText = ""
startbuttonLink = "#"
body_is_markdown = true
highlight = "#21b2a6"
#custom_css = "foo.css"
#images = ["path_to_social_image_for_link_previews.jpg"]

[[params.menu.main]]
url = '/'
title = "Home"

[[params.menu.main]]
url = '/posts/'
title = "Posts"

[taxonomies]
    tag = "tags"
    category = "categories"
    series = "series"

[params.one]
enable = true
title = 'Lowering AWS Bills is what we do!'
body = '''
Come talk to us and find out how we can save you money in AWS, be it optimisation or contract negotiation. SquareCows can bring FinOps to your organisation and help you control cloud spend.
'''

[[params.one.icon]]
icon = "regular fa-cow"
style = "1"
label = "Cow"

[[params.one.icon]]
icon = "regular fa-skull-cow"
style = "1"
label = "Cow Horns"

[[params.one.icon]]
icon = "regular fa-cowbell"
style = "1"
label = "Cow Bell"

[params.two]
enable = true

[[params.two.section]]
img = "img/cowshock.jpg"
title = 'Do you have bill shock?'
body = 'Let us use our 30+ years of experience to analyse and digest your bill into an easy to grasp report. We have experience across many verticles giving us a unquie view point to ensure we lower costs for you.'

[[params.two.section]]
img = "img/cows.jpg"
title = "One size doesn't fit all"
body = 'We know some solutions to lower your bill won’t work for everyone. This is why we work with you to tailor our solutions to your needs by getting to know your architecture and your business. This way, we can make sure you have a cost strategy that actually works for you.'

[[params.two.section]]
img = "img/cowsleeping.jpg"
title = "No boring reports"
body = 'We don’t like writing them and you don’t like reading them. Instead we will provide you with an executive summary and actionable items to make real cost savings quickly and efficiently.'

[params.three]
enable = true
title = 'Why work with SquareCows'
body = '''
You'll find working with SquareCows refreashing with a personal touch, allowing us to understand your needs and deliver results by taking a FinOps approach to your billing.
'''

[[params.three.feature]]
icon = "regular fa-briefcase"
title = "We work for you and not AWS"
body = "We partner with you and not AWS to get you savings from the off."

[[params.three.feature]]
icon = "solid fa-user-cowboy"
title = "30+ years experience"
body = "We have deep AWS knowledge gained by working with AWS services and working for AWS as solutions architects."

[[params.three.feature]]
icon = "regular fa-industry"
title = "Expertise across many verticles"
body = "From manufacturing to fintech via ecommerce and media, we have the experience that your business needs."

[[params.three.feature]]
icon = "regular fa-file-chart-pie"
title = "Simple, easy to understand reporting"
body = "Our reports are simple and easy to read, allowing you to make the changes to start saving money today."

[[params.three.feature]]
icon = "regular fa-money-check-dollar"
title = "Simple pricing"
body = "Cost optimisation reports £1000 per account, thats it."

[[params.three.feature]]
icon = "solid fa-megaphone"
title = "Consultancy"
body = "AWS Architecture and Linux Consultancy £1000 per day."

[params.cta]
enable = true
title = "Read our Blog"
body = "Find money saving tips in our blog and start saving today."

[[params.cta.link]]
href = "posts/"
text = "Read the blog"
special = true


[params.contact]
enable = true
title = "Contact"
body = "Leave us a message."
phone = "0800 046 5536"
address = "1234 Somewhere Road<br />Some Place, Some State 0000<br />Some Country"
email = "billshock@squarecows.com"
subject = "Website Message:"
formspree_form_id = "mlekglkp"

[params.social]
mastodon = "@sqcows"
github = "richarvey"
linkedin = "88641823"
youtube = "UCdaV9K31X9UkMOH4HgiS1_Q"

# language specific options

[languages.en]
weight = 0
languageName = "English"

